/*CATEGORIES*/
export const GET_CATEGORIES = "GET_CATEGORIES" ; 
export const GET_CATEGORY = "GET_CATEGORY"; 
export const CREATE_CATEGORY = "CREATE_CATEGORY" ; 
export const DELETE_CATEGORY = "DELETE_CATEGORY" ;

/*SUBCATEGORIES*/
export const GET_SUBCATEGORIES = "GET_SUBCATEGORIES" ; 
export const GET_SUBCATEGORY = "GET_SUBCATEGORY"; 
export const CREATE_SUBCATEGORY = "CREATE_SUBCATEGORY" ; 
export const DELETE_SUBCATEGORY = "DELETE_SUBCATEGORY" ;

/*POST*/
export const GET_POSTS = "GET_POSTS" ; 
export const CREATE_POST = "CREATE_POST"; 

